---
# handlers file for ansible-role-remotelog
- name: restart rsyslog
  service: name=rsyslog state=restarted
- name: Enable compress-remotelog timer
  systemd:
    name: compress-remotelog.timer
    state: started
    enabled: yes
    daemon_reload: yes
